baseurl: /
languageCode: en-us
title: A Fran website
theme: "hugo-lithium"
googleAnalytics: ''
disqusShortname: ''
ignoreFiles:
  # - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
# permalinks:
#     - post: /:year/:month/:day/:slug/
menu:
  main:
    - name: About
      url: /about/
    - name: Teaching
      url: /teaching/   
    - name: Employments
      url: /employments/  
    - name: Portfolio
      url: /portfolio/ 
    - name: GitHub
      url: https://github.com/Francisco-madrid-gambin
    - name: Linkedin
      url: https://www.linkedin.com/in/francisco-m-74489010a/
    - name: Modeling
      url: https://metabolomeconnectome.netlify.app/
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: Bla bla bla bla 3.
  favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: Logo
    height: 50
    url: logo.png
    width: 50
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes
